services:
  - type: web
    name: my-nodejs-app
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    branches:
      - main
    envVars:
      - key: NODE_ENV
        value: production
    github:
      repo: aramantonian/A